apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
      - name: demo
        env:
        - name: MODEL_SERVER_URL
          value: "http://58.229.121.146:8083"